name: scrape

# 允許 workflow push 回 repo
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5"   # 週一到週五 UTC 06:00

jobs:
  usgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python scraper/example_scraper.py
      - name: Commit USGS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "ci: update USGS data ($(date -u +%F))" || echo "no changes"
          git push

  wits:
    runs-on: ubuntu-latest
    needs: usgs   # 先跑完 USGS 再跑 WITS
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      # 未來若有 API 金鑰可改成 fetch_wits_api.py 並用 Secrets
      # - run: WITS_API_KEY=${{ secrets.WITS_API_KEY }} python scraper/wits/fetch_wits_api.py
      - run: python scraper/wits/fetch_wits.py
      - name: Commit WITS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "ci: update WITS data ($(date -u +%F))" || echo "no changes"
          git push


