name: scrape-usgs
on:
  workflow_dispatch:          # 允許手動觸發
  schedule:
    - cron: "0 6 * * *"       # 每天 06:00 UTC 自動跑一次（可改）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper/example_scraper.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.csv
          if ! git diff --cached --quiet; then
            git commit -m "ci: update USGS data ($(date -u +%F))"
            git push
          else
            echo "No changes"
          fi
